export interface KKProfilingRegistration {
  id: string;
  fullName: string;
  email: string;
  address: string;
  sex: string;
  age: number;
  birthDate: string | Date;
  facebook: string;
  contactNumber: string;
  civilStatus: string;
  youthClassification: string;
  youthAgeGroup: string;
  workStatus: string;
  educationalBackground: string;
  registeredSKVoter: string;
  votedLastSK: string;
  registeredNationalVoter: string;
  attendedKKAssembly: string;
  assemblyTimes?: string | null;
  noAssemblyReason?: string | null;
  consent?: boolean;
  idDocumentType?: string | null;
  idFrontFileUrl?: string | null;
  idBackFileUrl?: string | null;
  idSingleFileUrl?: string | null;
  reviewStatus?: string;
  reviewNotes?: string | null;
  submittedAt: string | Date;
}
